### ISSUE TITLE
Conflict with Oculus mixin

### ISSUE THREAD

**Issue by wsxiya** [Xaikii/FadingNightVision#1]

**Comment by Xaikii** [comment]
This had to become an incompat after an update of theirs, as I did test it locally with Embeddium and Oculus.
Please provide more info.
Logs, MC Version, (Neo)Forge Version, ModVersions of FadingNightVision, Oculus and Embeddium

**Comment by wsxiya** [comment]
> 在他们的更新之后，这必须成为一个不兼容的，因为我确实在本地用 Embeddium 和 Oculus 测试了它。请提供更多信息。 Logs、MC 版本、（Neo）Forge 版本、FadingNightVision、Oculus 和 Embeddium 的 Mod 版本

Below is my mod list and crash log
![SJZL9(5J1H 5BB}084YNZQG](https://github.com/user-attachments/assets/bde39368-f814-45a3-98c2-07a59e19d402)
[latest.log](https://github.com/user-attachments/files/16673725/latest.log)

**Comment by wsxiya** [comment]
minecraft1.20.1 forge47.2.17

**Comment by Xaikii** [comment]
Ty, will look into it as soon as I have time

**Comment by Xaikii** [comment]
forge or neoforge?
Just to be sure, because I mainly support NeoForge starting with 1.21

**Comment by wsxiya** [comment]
> Forge 还是 Neoforge？可以肯定的是，因为我主要支持 NeoForge

is forge, 1.20.1, because I used Sinytra Connector, and since it is not supported on 1.20.1neoforge

**Comment by Xaikii** [comment]
I uploaded a candidate (1.2.2) which should fix that.
I couldn't reproduce it at all in-dev, so I had to work with what is available from the log.

Please notify me if it worked :)

**Comment by wsxiya** [comment]
> 我上传了一个候选者（1.2.2），应该可以解决这个问题。我根本无法在开发中重现它，所以我不得不使用日志中可用的内容。
> 
> 如果它工作:)请告诉我

Version 1.2.2 can launch the game and does not crash, but the fade-out and fade-in animations do not work

**Comment by wsxiya** [comment]
Uploading 333.mp4…

**Comment by wsxiya** [comment]
https://github.com/user-attachments/assets/ab4ad090-8900-4c23-9a8f-e2d7f98184cb

**Comment by Xaikii** [comment]
I was able to reproduce it and now fully fixed it.
A new version was uploaded to CurseForge.
1.2.2.1 fixes this.

If it does reappear please open this issue again :)
